name: CI

on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout commit
        uses: actions/checkout@v2.4.0

      - name: Install Node
        uses: actions/setup-node@v2.5.1
        with:
          node-version: '16.x'

      - name: Install npm packages
        run: |
          set -e
          npm install

      - name: Build UI
        run: |
          set -e
          CI=false npm run build

      - name: Deploy
        if: github.repository == 'wooferzfg/instant-word-game' && github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          personal_token: ${{ secrets.GH_PAGES_DEPLOY }}
          force_orphan: true
          publish_branch: gh-pages
          publish_dir: ./build
